version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: text2vec-ollama
      ENABLE_MODULES: text2vec-ollama
      OLLAMA_API_ENDPOINT: 'http://host.docker.internal:11434'
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http