graph:
  similarity_threshold: 0.3
  max_keywords_per_paper: 10
  enable_author_similarity: true
  enable_citation_relationships: true

neo4j:
  # Connection settings
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "Vanya@28"  # Consider using environment variables for passwords in production
  database: "neo4j"
  initialize_schema: true
  connection_timeout: 30  # seconds
  max_connection_pool_size: 50
  
  # Schema configuration
  schema:
    # Node labels with recommended properties
    node_labels:
      Paper:
        properties:
          - name: "title"
            type: "string"
            indexed: true
            fulltext: true
          - name: "year"
            type: "integer"
            indexed: true
          - name: "doi"
            type: "string"
            unique: true
          - name: "citations_count"
            type: "integer"
            indexed: true
            
      Author:
        properties:
          - name: "name"
            type: "string"
            unique: true
            indexed: true
          - name: "orcid"
            type: "string"
            unique: false
            
      Institution:
        properties:
          - name: "name"
            type: "string"
            indexed: true
          - name: "country"
            type: "string"
            
      Journal:
        properties:
          - name: "name"
            type: "string"
            indexed: true
          - name: "issn"
            type: "string"
            unique: true
            
      Keyword:
        properties:
          - name: "keyword"
            type: "string"
            unique: true
            indexed: true
          - name: "normalized_form"
            type: "string"
            indexed: true
    
    # Relationship types with optional properties
    relationship_types:
      CITES:
        properties:
          - name: "citation_context"
            type: "string"
          - name: "year"
            type: "integer"
            
      AUTHORED_BY:
        properties:
          - name: "author_position"
            type: "integer"
            
      AFFILIATED_WITH:
        properties:
          - name: "start_year"
            type: "integer"
          - name: "end_year"
            type: "integer"
            
      PUBLISHED_IN:
        properties:
          - name: "volume"
            type: "string"
          - name: "issue"
            type: "string"
            
      HAS_KEYWORD:
        properties:
          - name: "weight"
            type: "float"
            
      SIMILAR_TO:
        properties:
          - name: "similarity_score"
            type: "float"
          - name: "algorithm"
            type: "string"
            
      COLLABORATES_WITH:
        properties:
          - name: "collaboration_count"
            type: "integer"
          - name: "last_collaboration_year"
            type: "integer"
    
    # Full-text search configuration
    fulltext_indexes:
      - name: "paper_content_index"
        labels: ["Paper"]
        properties: ["title", "abstract", "keywords", "main_findings"]
        analyzer: "english"  # Language-specific analyzer

weaviate:
  host: "localhost"
  port: 8080
  scheme: "http"
  openai_api_key: "your-openai-api-key"  # Required if using OpenAI embeddings
  class_name: "ResearchPaper"
  vectorizer: "text2vec-openai"  # Alternatives: "none", "text2vec-transformers", etc.
  properties:
    - name: "title"
      dataType: ["text"]
    - name: "authors"
      dataType: ["text[]"]
    - name: "year"
      dataType: ["int"]
    - name: "keywords"
      dataType: ["text[]"]
    - name: "abstract"
      dataType: ["text"]
  additional_config:
    batch_size: 100
    dynamic_batching: true
    vector_index_type: "hnsw"  # Alternatives: "flat"
    vector_index_config:
      distance_metric: "cosine"
      efConstruction: 128
      maxConnections: 64

data:
  required_columns:
    - "Title"
    - "Author(s)" 
    - "Keywords"
    - "Year"
  optional_columns:
    - "Journal/Conference"
    - "Methodology"
    - "Main Findings"
    - "Citations (est.)"
    - "DOI/Link"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/research_graph.log"

storage:
  graph_cache_dir: "data/graphs"
  processed_data_dir: "data/processed"
  vector_store_dir: "data/vectors"
  enable_caching: true